export const SET_EMAIL = 'SET_EMAIL';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_LOADING = 'SET_LOADING';
export const SET_QUESTIONS_FETCHED = 'SET_QUESTIONS_FETCHED';
export const SET_TRANSFORM = 'SET_TRANSFORM';
export const SET_ANSWER = 'SET_ANSWER';